### ISSUE TITLE
Subfield Segmentation

### ISSUE THREAD

**Issue by DavidMolitor92** [jordandekraker/HippUnfolding#3]
Hi @jordandekraker, 
first let me thank you for sharing your code with the community. I'm currently working on something similiar and i have a couple of questions.
At first: How did you find the borders for subfield segmentation in the unfolded space? I'm more interested in finding the borders for each individual, than projecting the average borders on their unfolded maps. 
Citing from the paper: 

> That is, for each manually segmented hippocampus, we found the longitudinal and proximal-distal coordinates which correspond to each of the subfield borders.

And second: How did you define the borders between the vertical component, the uncus, head, body and tail? In the code
`x = [5 18]; y = [1,100]; plot(x,y,'--k'); %vertical component
x = [20 28]; y = [1,100]; plot(x,y,'--k'); %uncus
x = [36 40]; y = [1,100]; plot(x,y,'--k'); %head
x = [84 80]; y = [1,100]; plot(x,y,'--k'); %tail`
you define them through gradients. But are they based on the anatomy or are they based on atlases? 

Thanks for your help.
Greetings
David

**Comment by jordandekraker** [comment]
Hi David,
Glad you can get some use out of this code! I can think of a few ways to get the subfield borders in unfolded space, if you want to use exactly the code i used I can dig it up and post it on Monday. Otherwise you could do something like this:

load([unfolded_fn '/data.mat']);
SEGimage= load_untouch_nii('SEGimage.nii.gz');
SEGimage= double(SEGimage.img);
Laplace_PD = ceil(Laplace_PD*100) %if they are not already, bin the gradients
Laplace_AP = ceil(Laplace_AP*100) 
flatmap = nan(100,100) %initialize
for AP = 1:100
  for PD = 1:100
    nativeCoords = find(Laplace_AP==AP & Laplace_PD==PD);
    if ~isempty(nativeCoords)
      flatmap(AP,PD) = median(SEGimage(nativeCoords));
    end
  end
end
imagesc(flatmap); %this should now show each subfield in a different color in unfolded space
You should be able to get the coordinates of the borders between regions in that space pretty easily from there, but feel free to message me for that too.

As for the vert. unc, uncus, head, body, and tail borders, we actually didn't define them very stringently in this project. I basically just drew a straight line through unfolded space in a position that, in the two example cases used throughout the paper, appeared (visually) to most closely correspond to each of these borders. Thus these borders shouldn't be used for formal analyses (we included them as a rough approximation mainly to help people get oriented in the unfolded space). However if you're interested in defining them more precisely them then I'd recommend doing it in each participants' native space and then finding the border location in unfolded space as in the code above. 

Hope that helps, and I'm happy to help with any other questions!
Cheers,
Jordan

**Comment by DavidMolitor92** [comment]
Hey,  
Tanks for the quick reply and sorry for my late response. Actually it'd be quite nice from you if you could dig up the old code. Unfortunately I had an other issue last week, when I tried to install the program on another PC with MATLAB R015b and the laplace_iters.mex file didn't work. In the readme you wrote one should try to run the project-file with the coder? How exactly does that work? And did you mean the MATLAB Coder extension?
Thanks again,
Greetings
David

**Comment by jordandekraker** [comment]
Happy to help. You should be able to open subfunctions/laplace_iters_mex.prj
using the MATLAB Coder and just follow the instructions to get everything
working.

Attached is the code I used in my project. You'll have to modify it with
the appropriate filenames, and I wrote this code quite a while ago so it
may not be the most efficient method. Still, should be enough to get you
started.

I should also note that I'll soon be adding another function to this
repository that modified the anterior-posterior laplacian solution in order
to make it more orthogonal to the proximal-distal laplacian, meaning that
the unfolded space representation has no empty space. In principle the A-P
solution will still be a laplacian gradient, but the boundary conditions
will be modified slightly to correct for manual segmentation errors. This
is a relatively minor change, but it just cleans things up a little bit.
Will probably be posted by tomorrow.

Cheers,
Jordan

**Comment by DavidMolitor92** [comment]
Hey, 
I got the Coder working, but for some reason i needed to change a line in laplace_solver First! In line 91 it took a change from laplace_iters_mex to laplace_iters and that did the job. 
Thanks again for the code and the help. 
Greetings
David

**Comment by jordandekraker** [comment]
Sounds good, glad you found a solution!

If you want to improve the processing speed, you are now using the non-mex version of laplace_iters. If you successfully mex that file with the included laplace_iters_mex.prj in the MATLAB Coder, then that will run significantly faster!

Hope your project unfolds successfully,
Jordan
